- block: 
  - name: Create AUR user
    user:
      name: "{{ aur_builder.user }}"
      group: "{{ aur_builder.group }}"
  - name: "Add AUR user to sudoers"
    lineinfile:
      path: /etc/sudoers.d/11-aur-builder
      line: '{{ aur_builder.user }} ALL=(ALL) NOPASSWD:ALL'
      create: yes
      validate: 'visudo -cf %s'
  become: yes
- name: Create ansible tmp directory for AUR user
  ansible.builtin.file:
    path: '/home/{{ aur_builder.user }}/.ansible/tmp'
    state: directory
    mode: '0755'
    owner: '{{ aur_builder.user }}'
